// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: proto/house.proto

package house

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aid string `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Sd  string `protobuf:"bytes,2,opt,name=sd,proto3" json:"sd,omitempty"`
	Ed  string `protobuf:"bytes,3,opt,name=ed,proto3" json:"ed,omitempty"`
	Sk  string `protobuf:"bytes,4,opt,name=sk,proto3" json:"sk,omitempty"`
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *SearchReq) GetSd() string {
	if x != nil {
		return x.Sd
	}
	return ""
}

func (x *SearchReq) GetEd() string {
	if x != nil {
		return x.Ed
	}
	return ""
}

func (x *SearchReq) GetSk() string {
	if x != nil {
		return x.Sk
	}
	return ""
}

type IndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndexReq) Reset() {
	*x = IndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexReq) ProtoMessage() {}

func (x *IndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexReq.ProtoReflect.Descriptor instead.
func (*IndexReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{1}
}

type DetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseId  string `protobuf:"bytes,1,opt,name=houseId,proto3" json:"houseId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *DetailReq) Reset() {
	*x = DetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailReq) ProtoMessage() {}

func (x *DetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailReq.ProtoReflect.Descriptor instead.
func (*DetailReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{2}
}

func (x *DetailReq) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

func (x *DetailReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string      `protobuf:"bytes,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Data    *DetailData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DetailResp) Reset() {
	*x = DetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResp) ProtoMessage() {}

func (x *DetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResp.ProtoReflect.Descriptor instead.
func (*DetailResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{3}
}

func (x *DetailResp) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *DetailResp) GetData() *DetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DetailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	House  *HouseDetail `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	UserId int32        `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DetailData) Reset() {
	*x = DetailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailData) ProtoMessage() {}

func (x *DetailData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailData.ProtoReflect.Descriptor instead.
func (*DetailData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{4}
}

func (x *DetailData) GetHouse() *HouseDetail {
	if x != nil {
		return x.House
	}
	return nil
}

func (x *DetailData) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HouseDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acreage  int32  `protobuf:"varint,1,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Beds     string `protobuf:"bytes,3,opt,name=beds,proto3" json:"beds,omitempty"`
	Capacity int32  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// comment
	Comments []*CommentData `protobuf:"bytes,5,rep,name=comments,proto3" json:"comments,omitempty"`
	Deposit  int32          `protobuf:"varint,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	// 展示所有的图片 主图片和副图片
	Facilities []int32  `protobuf:"varint,7,rep,packed,name=facilities,proto3" json:"facilities,omitempty"` //家具id切片
	Hid        int32    `protobuf:"varint,8,opt,name=hid,proto3" json:"hid,omitempty"`
	ImgUrls    []string `protobuf:"bytes,9,rep,name=imgUrls,proto3" json:"imgUrls,omitempty"`
	MaxDays    int32    `protobuf:"varint,10,opt,name=maxDays,proto3" json:"maxDays,omitempty"`
	MinDays    int32    `protobuf:"varint,11,opt,name=minDays,proto3" json:"minDays,omitempty"`
	Price      int32    `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount  int32    `protobuf:"varint,13,opt,name=roomCount,proto3" json:"roomCount,omitempty"`
	Title      string   `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`
	Unit       string   `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	UserAvatar string   `protobuf:"bytes,16,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
	UserId     int32    `protobuf:"varint,17,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName   string   `protobuf:"bytes,18,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *HouseDetail) Reset() {
	*x = HouseDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseDetail) ProtoMessage() {}

func (x *HouseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseDetail.ProtoReflect.Descriptor instead.
func (*HouseDetail) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{5}
}

func (x *HouseDetail) GetAcreage() int32 {
	if x != nil {
		return x.Acreage
	}
	return 0
}

func (x *HouseDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HouseDetail) GetBeds() string {
	if x != nil {
		return x.Beds
	}
	return ""
}

func (x *HouseDetail) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HouseDetail) GetComments() []*CommentData {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *HouseDetail) GetDeposit() int32 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *HouseDetail) GetFacilities() []int32 {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *HouseDetail) GetHid() int32 {
	if x != nil {
		return x.Hid
	}
	return 0
}

func (x *HouseDetail) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *HouseDetail) GetMaxDays() int32 {
	if x != nil {
		return x.MaxDays
	}
	return 0
}

func (x *HouseDetail) GetMinDays() int32 {
	if x != nil {
		return x.MinDays
	}
	return 0
}

func (x *HouseDetail) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *HouseDetail) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *HouseDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseDetail) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *HouseDetail) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *HouseDetail) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HouseDetail) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CommentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment  string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime    string `protobuf:"bytes,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *CommentData) Reset() {
	*x = CommentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentData) ProtoMessage() {}

func (x *CommentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentData.ProtoReflect.Descriptor instead.
func (*CommentData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{6}
}

func (x *CommentData) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CommentData) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

func (x *CommentData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{7}
}

func (x *GetReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string   `protobuf:"bytes,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Data    *GetData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{8}
}

func (x *GetResp) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *GetResp) GetData() *GetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Houses []*Houses `protobuf:"bytes,1,rep,name=houses,proto3" json:"houses,omitempty"`
}

func (x *GetData) Reset() {
	*x = GetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetData) ProtoMessage() {}

func (x *GetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetData.ProtoReflect.Descriptor instead.
func (*GetData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{9}
}

func (x *GetData) GetHouses() []*Houses {
	if x != nil {
		return x.Houses
	}
	return nil
}

type Houses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AreaName   string `protobuf:"bytes,2,opt,name=areaName,proto3" json:"areaName,omitempty"`
	Ctime      string `protobuf:"bytes,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	HouseId    int32  `protobuf:"varint,4,opt,name=houseId,proto3" json:"houseId,omitempty"`
	ImgUrl     string `protobuf:"bytes,5,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	OrderCount int32  `protobuf:"varint,6,opt,name=orderCount,proto3" json:"orderCount,omitempty"`
	Price      int32  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount  int32  `protobuf:"varint,8,opt,name=roomCount,proto3" json:"roomCount,omitempty"`
	Title      string `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	UserAvatar string `protobuf:"bytes,10,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
}

func (x *Houses) Reset() {
	*x = Houses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Houses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Houses) ProtoMessage() {}

func (x *Houses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Houses.ProtoReflect.Descriptor instead.
func (*Houses) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{10}
}

func (x *Houses) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Houses) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *Houses) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

func (x *Houses) GetHouseId() int32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *Houses) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *Houses) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Houses) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Houses) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *Houses) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Houses) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

type ImgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseId string `protobuf:"bytes,1,opt,name=houseId,proto3" json:"houseId,omitempty"`
	ImgData []byte `protobuf:"bytes,2,opt,name=imgData,proto3" json:"imgData,omitempty"`
	FileExt string `protobuf:"bytes,3,opt,name=fileExt,proto3" json:"fileExt,omitempty"`
}

func (x *ImgReq) Reset() {
	*x = ImgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgReq) ProtoMessage() {}

func (x *ImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgReq.ProtoReflect.Descriptor instead.
func (*ImgReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{11}
}

func (x *ImgReq) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

func (x *ImgReq) GetImgData() []byte {
	if x != nil {
		return x.ImgData
	}
	return nil
}

func (x *ImgReq) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

type ImgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string   `protobuf:"bytes,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Data    *ImgData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ImgResp) Reset() {
	*x = ImgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgResp) ProtoMessage() {}

func (x *ImgResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgResp.ProtoReflect.Descriptor instead.
func (*ImgResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{12}
}

func (x *ImgResp) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *ImgResp) GetData() *ImgData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ImgData) Reset() {
	*x = ImgData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgData) ProtoMessage() {}

func (x *ImgData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgData.ProtoReflect.Descriptor instead.
func (*ImgData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{13}
}

func (x *ImgData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acreage   string   `protobuf:"bytes,1,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Address   string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AreaId    string   `protobuf:"bytes,3,opt,name=areaId,proto3" json:"areaId,omitempty"`
	Beds      string   `protobuf:"bytes,4,opt,name=beds,proto3" json:"beds,omitempty"`
	Capacity  string   `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Deposit   string   `protobuf:"bytes,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Facility  []string `protobuf:"bytes,7,rep,name=facility,proto3" json:"facility,omitempty"`
	MaxDays   string   `protobuf:"bytes,8,opt,name=maxDays,proto3" json:"maxDays,omitempty"`
	MinDays   string   `protobuf:"bytes,9,opt,name=minDays,proto3" json:"minDays,omitempty"`
	Price     string   `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount string   `protobuf:"bytes,11,opt,name=roomCount,proto3" json:"roomCount,omitempty"`
	Title     string   `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	Unit      string   `protobuf:"bytes,13,opt,name=unit,proto3" json:"unit,omitempty"`
	UserName  string   `protobuf:"bytes,14,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{14}
}

func (x *Request) GetAcreage() string {
	if x != nil {
		return x.Acreage
	}
	return ""
}

func (x *Request) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Request) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *Request) GetBeds() string {
	if x != nil {
		return x.Beds
	}
	return ""
}

func (x *Request) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *Request) GetDeposit() string {
	if x != nil {
		return x.Deposit
	}
	return ""
}

func (x *Request) GetFacility() []string {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *Request) GetMaxDays() string {
	if x != nil {
		return x.MaxDays
	}
	return ""
}

func (x *Request) GetMinDays() string {
	if x != nil {
		return x.MinDays
	}
	return ""
}

func (x *Request) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Request) GetRoomCount() string {
	if x != nil {
		return x.RoomCount
	}
	return ""
}

func (x *Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Request) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string     `protobuf:"bytes,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Data    *HouseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{15}
}

func (x *Response) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *Response) GetData() *HouseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HouseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseId string `protobuf:"bytes,1,opt,name=houseId,proto3" json:"houseId,omitempty"`
}

func (x *HouseData) Reset() {
	*x = HouseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_house_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseData) ProtoMessage() {}

func (x *HouseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseData.ProtoReflect.Descriptor instead.
func (*HouseData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{16}
}

func (x *HouseData) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

var File_proto_house_proto protoreflect.FileDescriptor

var file_proto_house_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0x4d, 0x0a, 0x09, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6b, 0x22, 0x0a, 0x0a, 0x08, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x52, 0x65, 0x71, 0x22, 0x41, 0x0a, 0x09, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0a, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x0a, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xed, 0x03, 0x0a, 0x0b, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x72, 0x65, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x63, 0x72, 0x65, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x65, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x65, 0x64, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x68, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x55, 0x72,
	0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69,
	0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x24, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x06,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x52, 0x06, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x73, 0x22, 0x90, 0x02, 0x0a, 0x06, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x56, 0x0a, 0x06, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x69, 0x6d, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x22, 0x47,
	0x0a, 0x07, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0xe9, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x72, 0x65, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x72, 0x65, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x65, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x65, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x4a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x09,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x49, 0x64, 0x32, 0xba, 0x02, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x08, 0x50, 0x75, 0x62, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x2e, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6d, 0x67, 0x12, 0x0d,
	0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x2f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0d, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0f, 0x2e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x10, 0x2e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_house_proto_rawDescOnce sync.Once
	file_proto_house_proto_rawDescData = file_proto_house_proto_rawDesc
)

func file_proto_house_proto_rawDescGZIP() []byte {
	file_proto_house_proto_rawDescOnce.Do(func() {
		file_proto_house_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_house_proto_rawDescData)
	})
	return file_proto_house_proto_rawDescData
}

var file_proto_house_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_house_proto_goTypes = []interface{}{
	(*SearchReq)(nil),   // 0: house.SearchReq
	(*IndexReq)(nil),    // 1: house.IndexReq
	(*DetailReq)(nil),   // 2: house.DetailReq
	(*DetailResp)(nil),  // 3: house.DetailResp
	(*DetailData)(nil),  // 4: house.DetailData
	(*HouseDetail)(nil), // 5: house.HouseDetail
	(*CommentData)(nil), // 6: house.CommentData
	(*GetReq)(nil),      // 7: house.GetReq
	(*GetResp)(nil),     // 8: house.GetResp
	(*GetData)(nil),     // 9: house.GetData
	(*Houses)(nil),      // 10: house.Houses
	(*ImgReq)(nil),      // 11: house.ImgReq
	(*ImgResp)(nil),     // 12: house.ImgResp
	(*ImgData)(nil),     // 13: house.ImgData
	(*Request)(nil),     // 14: house.Request
	(*Response)(nil),    // 15: house.Response
	(*HouseData)(nil),   // 16: house.HouseData
}
var file_proto_house_proto_depIdxs = []int32{
	4,  // 0: house.DetailResp.data:type_name -> house.DetailData
	5,  // 1: house.DetailData.house:type_name -> house.HouseDetail
	6,  // 2: house.HouseDetail.comments:type_name -> house.CommentData
	9,  // 3: house.GetResp.data:type_name -> house.GetData
	10, // 4: house.GetData.houses:type_name -> house.Houses
	13, // 5: house.ImgResp.data:type_name -> house.ImgData
	16, // 6: house.Response.data:type_name -> house.HouseData
	14, // 7: house.House.PubHouse:input_type -> house.Request
	11, // 8: house.House.UploadHouseImg:input_type -> house.ImgReq
	7,  // 9: house.House.GetHouseInfo:input_type -> house.GetReq
	2,  // 10: house.House.GetHouseDetail:input_type -> house.DetailReq
	1,  // 11: house.House.GetIndexHouse:input_type -> house.IndexReq
	0,  // 12: house.House.SearchHouse:input_type -> house.SearchReq
	15, // 13: house.House.PubHouse:output_type -> house.Response
	12, // 14: house.House.UploadHouseImg:output_type -> house.ImgResp
	8,  // 15: house.House.GetHouseInfo:output_type -> house.GetResp
	3,  // 16: house.House.GetHouseDetail:output_type -> house.DetailResp
	8,  // 17: house.House.GetIndexHouse:output_type -> house.GetResp
	8,  // 18: house.House.SearchHouse:output_type -> house.GetResp
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_house_proto_init() }
func file_proto_house_proto_init() {
	if File_proto_house_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_house_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Houses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_house_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_house_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_house_proto_goTypes,
		DependencyIndexes: file_proto_house_proto_depIdxs,
		MessageInfos:      file_proto_house_proto_msgTypes,
	}.Build()
	File_proto_house_proto = out.File
	file_proto_house_proto_rawDesc = nil
	file_proto_house_proto_goTypes = nil
	file_proto_house_proto_depIdxs = nil
}
